# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/workspace/yacc/yacc_main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_yacc_main_window(object):
    def setupUi(self, yacc_main_window):
        yacc_main_window.setObjectName(_fromUtf8("yacc_main_window"))
        yacc_main_window.resize(841, 352)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(yacc_main_window.sizePolicy().hasHeightForWidth())
        yacc_main_window.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(yacc_main_window)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.mix_box = QtGui.QComboBox(self.centralwidget)
        self.mix_box.setMinimumSize(QtCore.QSize(200, 0))
        self.mix_box.setObjectName(_fromUtf8("mix_box"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.mix_box)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.totalvol_box = QtGui.QLineEdit(self.centralwidget)
        self.totalvol_box.setMaximumSize(QtCore.QSize(50, 16777215))
        self.totalvol_box.setObjectName(_fromUtf8("totalvol_box"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.totalvol_box)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.nic_box = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nic_box.sizePolicy().hasHeightForWidth())
        self.nic_box.setSizePolicy(sizePolicy)
        self.nic_box.setMaximumSize(QtCore.QSize(50, 16777215))
        self.nic_box.setObjectName(_fromUtf8("nic_box"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.nic_box)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_2)
        self.vg_box = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vg_box.sizePolicy().hasHeightForWidth())
        self.vg_box.setSizePolicy(sizePolicy)
        self.vg_box.setMinimumSize(QtCore.QSize(50, 0))
        self.vg_box.setMaximumSize(QtCore.QSize(50, 16777215))
        self.vg_box.setFrame(True)
        self.vg_box.setObjectName(_fromUtf8("vg_box"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.vg_box)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.recipe_box = QtGui.QComboBox(self.centralwidget)
        self.recipe_box.setMinimumSize(QtCore.QSize(200, 0))
        self.recipe_box.setObjectName(_fromUtf8("recipe_box"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.recipe_box)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.update_button = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_button.setFont(font)
        self.update_button.setObjectName(_fromUtf8("update_button"))
        self.horizontalLayout_2.addWidget(self.update_button)
        self.reload_button = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reload_button.setFont(font)
        self.reload_button.setObjectName(_fromUtf8("reload_button"))
        self.horizontalLayout_2.addWidget(self.reload_button)
        self.redit_button = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.redit_button.setFont(font)
        self.redit_button.setObjectName(_fromUtf8("redit_button"))
        self.horizontalLayout_2.addWidget(self.redit_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.output_box = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_box.sizePolicy().hasHeightForWidth())
        self.output_box.setSizePolicy(sizePolicy)
        self.output_box.setMinimumSize(QtCore.QSize(500, 0))
        self.output_box.setReadOnly(True)
        self.output_box.setObjectName(_fromUtf8("output_box"))
        self.horizontalLayout.addWidget(self.output_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        yacc_main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(yacc_main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        yacc_main_window.setMenuBar(self.menubar)
        self.status_bar = QtGui.QStatusBar(yacc_main_window)
        self.status_bar.setObjectName(_fromUtf8("status_bar"))
        yacc_main_window.setStatusBar(self.status_bar)
        self.actionOpen_File = QtGui.QAction(yacc_main_window)
        self.actionOpen_File.setObjectName(_fromUtf8("actionOpen_File"))
        self.actionExit = QtGui.QAction(yacc_main_window)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAdd_Recipes = QtGui.QAction(yacc_main_window)
        self.actionAdd_Recipes.setObjectName(_fromUtf8("actionAdd_Recipes"))
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionAdd_Recipes)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(yacc_main_window)
        QtCore.QMetaObject.connectSlotsByName(yacc_main_window)

    def retranslateUi(self, yacc_main_window):
        yacc_main_window.setWindowTitle(_translate("yacc_main_window", "YACC - Yet Another Cloud Calculator", None))
        self.label.setText(_translate("yacc_main_window", "Mix Type", None))
        self.label_4.setText(_translate("yacc_main_window", "Total Volume [mL]", None))
        self.label_3.setText(_translate("yacc_main_window", "Nicotine [mg/mL]", None))
        self.label_2.setText(_translate("yacc_main_window", "VG [%]", None))
        self.label_5.setText(_translate("yacc_main_window", "Recipe", None))
        self.update_button.setText(_translate("yacc_main_window", "Update", None))
        self.reload_button.setText(_translate("yacc_main_window", "Reload", None))
        self.redit_button.setText(_translate("yacc_main_window", "Edit Recipes", None))
        self.menuFile.setTitle(_translate("yacc_main_window", "Fi&le", None))
        self.actionOpen_File.setText(_translate("yacc_main_window", "&Open File", None))
        self.actionExit.setText(_translate("yacc_main_window", "&Exit", None))
        self.actionAdd_Recipes.setText(_translate("yacc_main_window", "&Add Recipes", None))

